### ISSUE TITLE
2.8.1: LV2 plugin fails on lv2lint

### ISSUE THREAD

**Issue by dvzrv** [free-sm/geonkick#164] opened 2022-01-16 09:41 UTC
Hi! When building 2.8.1 for Arch Linux I ran lv2lint against the plugin as usual. Unfortunately this fails due to globally visible symbols:

```
lv2lint 0.14.0
Copyright (c) 2016-2021 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
<http://geontime.com/geonkick>
    [FAIL]  Plugin Symbols
              binary exports superfluous globally visible symbols:
                * _ZTISt18bad_variant_access
                * _ZTSSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJM9KickGraphFvvEPS3_EEEEEE
                * _ZTSSt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZSt19piecewise_construct
                * _ZTISt19_Sp_make_shared_tag
                * _ZTSSt19_Sp_make_shared_tag
                * _ZTISt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTISt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTSSt18bad_variant_access
                * ... there is more, but the rest is being truncated
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
  <http://geontime.com/geonkick#ui>
    [FAIL]  UI Symbols
              binary exports superfluous globally visible symbols:
                * _ZTISt18bad_variant_access
                * _ZTSSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJM9KickGraphFvvEPS3_EEEEEE
                * _ZTSSt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZSt19piecewise_construct
                * _ZTISt19_Sp_make_shared_tag
                * _ZTSSt19_Sp_make_shared_tag
                * _ZTISt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTISt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTSSt18bad_variant_access
                * ... there is more, but the rest is being truncated
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
    [WARN]  UI Instance Access
              usage of instance-access is highly discouraged
              seeAlso: <http://lv2plug.in/ns/ext/instance-access>
    [WARN]  UI Mixed DSP/UI
              mixing DSP and UI code in same binary is discouraged
              seeAlso: <http://lv2plug.in/ns/extensions/ui#>
```

**Comment by iurienistor** [comment] 2022-01-16 10:34
@dvzrv I haven't change anything. Thus, I'll check why now new symbols are seen. If you find something, please, make a pull request.

**Comment by iurienistor** [comment] 2022-01-16 10:59
@dvzrv Sincerely I don't understand how this tool is supposed to work, but I have installed the last version and it gives things that doesn't make sense. I don't understand why other plugins have to do here: 

```
"lv2lint -I /usr/local/lib/lv2/geonkick.lv2/ "http://geontime.com/geonkick"
lv2lint 0.15.1
Copyright (c) 2016-2021 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
error: failed to open file /usr/lib/lv2/gx_colwah.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/gx_colwah.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/gx_colwah.lv2/manifest.ttl
error: failed to open file /usr/local/lib/lv2/Linux-64b-LV2-FREE.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/Linux-64b-LV2-FREE.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/local/lib/lv2/Linux-64b-LV2-FREE.lv2/manifest.ttl
error: failed to open file /usr/local/lib/lv2/DragonflyPlateReverb.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/DragonflyPlateReverb.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/local/lib/lv2/DragonflyPlateReverb.lv2/manifest.ttl
error: failed to open file /usr/local/lib/lv2/DragonflyHallReverb.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/DragonflyHallReverb.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/local/lib/lv2/DragonflyHallReverb.lv2/manifest.ttl
error: failed to open file /usr/local/lib/lv2/DragonflyEarlyReflections.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/DragonflyEarlyReflections.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/local/lib/lv2/DragonflyEarlyReflections.lv2/manifest.ttl
error: failed to open file /usr/local/lib/lv2/sfizz.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/sfizz.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/local/lib/lv2/sfizz.lv2/manifest.ttl
error: failed to open file /usr/local/lib/lv2/DragonflyRoomReverb.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/local/lib/lv2/DragonflyRoomReverb.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/local/lib/lv2/DragonflyRoomReverb.lv2/manifest.ttl
lilv_world_add_plugin(): warning: Reloading plugin <http://geontime.com/geonkick>
lilv_world_add_plugin(): warning: Reloading plugin <http://geontime.com/geonkick/single>
<http://geontime.com/geonkick>
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)
```
"

**Comment by iurienistor** [comment] 2022-01-16 11:10
@dvzrv Is there another tool which can validate LV2 plugin?

**Comment by iurienistor** [comment] 2022-01-16 14:22
@dvzrv I don't know why these symbols are treated global by lv2lint because for the shared library I have this result:

nm -D ./geonkick_lv2.so | grep 'T \| A\| B\| D\| S'
0000000000029080 T lv2_descriptor
0000000000029060 T lv2ui_descriptor

**Comment by dvzrv** [comment] 2022-01-16 14:38
@iurienistor I copy the .so files after build:

https://github.com/archlinux/svntogit-community/blob/d59bc4615a13c78578985189c8b73f8064e35eff/trunk/PKGBUILD#L32-L34

I'm not entirely sure why this is now different from before, but it worked with the previous version AFAIK.

**Comment by dvzrv** [comment] 2022-01-29 17:23
@iurienistor why did you close this as invalid?

I have used lv2lint for *many* lv2 plugins and projects already...

**Comment by dvzrv** [comment] 2022-01-29 17:35
When ignoring the failing tests and installing the plugin, I can reproduce this in a system-wide location:

```
lv2lint -Mpack -I /usr/lib/lv2/geonkick.lv2 "http://geontime.com/geonkick"
lv2lint 0.14.0
Copyright (c) 2016-2021 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
lilv_world_add_plugin(): warning: Reloading plugin <http://geontime.com/geonkick>
lilv_world_add_plugin(): warning: Reloading plugin <http://geontime.com/geonkick/single>
<http://geontime.com/geonkick>
    [FAIL]  Plugin Symbols
              binary exports superfluous globally visible symbols:
                * _ZTISt18bad_variant_access
                * _ZTSSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJM9KickGraphFvvEPS3_EEEEEE
                * _ZTSSt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZSt19piecewise_construct
                * _ZTISt19_Sp_make_shared_tag
                * _ZTSSt19_Sp_make_shared_tag
                * _ZTISt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTISt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTSSt18bad_variant_access
                * ... there is more, but the rest is being truncated
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
  <http://geontime.com/geonkick#ui>
    [FAIL]  UI Symbols
              binary exports superfluous globally visible symbols:
                * _ZTISt18bad_variant_access
                * _ZTSSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJM9KickGraphFvvEPS3_EEEEEE
                * _ZTSSt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZSt19piecewise_construct
                * _ZTISt19_Sp_make_shared_tag
                * _ZTSSt19_Sp_make_shared_tag
                * _ZTISt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTISt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE
                * _ZTSSt18bad_variant_access
                * ... there is more, but the rest is being truncated
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
    [WARN]  UI Instance Access
              usage of instance-access is highly discouraged
              seeAlso: <http://lv2plug.in/ns/ext/instance-access>
    [WARN]  UI Mixed DSP/UI
              mixing DSP and UI code in same binary is discouraged
              seeAlso: <http://lv2plug.in/ns/extensions/ui#>
```

@ventosus as the author of lv2lint can maybe elaborate on what is going wrong here. Should I be allowing all of the globally exposed symbols one by one? There seem to be many and I never had to do this manually this way.

**Comment by falkTX** [comment] 2022-01-29 17:43
it likely just needs `-fvisibility=hidden` in the default build flags for release mode.

**Comment by iurienistor** [comment] 2022-01-30 10:48
@falkTX In the project CMakeLists.txt there is:

```
set(CMAKE_CXX_FLAGS "-Wall ${GKICK_OPTIMISATION_FLAGS} ${CMAKE_CXX_FLAGS} -fvisibility=hidden")
set(CMAKE_C_FLAGS "-Wall ${GKICK_OPTIMISATION_FLAGS} ${CMAKE_C_FLAGS} -fvisibility=hidden")

```

from my point of view this should use -fvisibility=hidden regardless of CMAKE_BUILD_TYPE.

**Comment by falkTX** [comment] 2022-01-30 16:06
I disagree. If we want to debug things, the hidden symbols are a pain.
So IMO `-fvisibility=hidden` should be part of optimization flags

**Comment by iurienistor** [comment] 2022-01-30 17:10
@falkTX I meant that the actual state of things hides the symbols, even for release but lv2lint still say that there are global visible symbols.

**Comment by falkTX** [comment] 2022-01-30 17:35
right, what might be needed here is a linker script that purposefully hides everything but a well defined list of symbols.

I use this in DPF:
https://github.com/DISTRHO/DPF/blob/develop/utils/symbols/lv2.version
together with `-Wl,--version-script=$(DPF_PATH)/utils/symbols/lv2.version`

lv2lint is not wrong, it complains about regular things.
it is just that we used to ignore those before I guess hoping everything still works.

**Comment by ventosus** [comment] 2022-01-30 18:32
terminate called after throwing an instance of 'std::system_error'
      what():  Invalid argument
    Aborted (core dumped)

@iurienistor I get that too with lv2lint built with x11-tests=enabled, @dvzrv uses a version with x11-tests=disabled

**Comment by ventosus** [comment] 2022-01-30 18:56
As for the visible symbols, I cannot reproduce here on *Parabola GNU/Linux-libre*, lv2lint runs through just fine w/o x11 tests.

    $ gcc --version
    gcc (GCC) 11.1.0


    $ lv2lint -Mpack $( lv2ls | grep geon )
    lv2lint 0.15.1
    Copyright (c) 2016-2021 Hanspeter Portner (dev@open-music-kontrollers.ch)
    Released under Artistic License 2.0 by Open Music Kontrollers
    <http://geontime.com/geonkick>
    <http://geontime.com/geonkick#ui>
    [WARN]  UI Instance Access
              usage of instance-access is highly discouraged
              seeAlso: <http://lv2plug.in/ns/ext/instance-access>
    [WARN]  UI Mixed DSP/UI
              mixing DSP and UI code in same binary is discouraged
              seeAlso: <http://lv2plug.in/ns/extensions/ui#>
    [FAIL]  UI Idle Interface
              lv2:feature ui:idleInterface missing
              seeAlso: <http://lv2plug.in/ns/extensions/ui#idleInterface>

    <http://geontime.com/geonkick/single>
    <http://geontime.com/geonkick/single#ui>
    [WARN]  UI Instance Access
              usage of instance-access is highly discouraged
              seeAlso: <http://lv2plug.in/ns/ext/instance-access>
    [WARN]  UI Mixed DSP/UI
              mixing DSP and UI code in same binary is discouraged
              seeAlso: <http://lv2plug.in/ns/extensions/ui#>
    [FAIL]  UI Idle Interface
              lv2:feature ui:idleInterface missing
              seeAlso: <http://lv2plug.in/ns/extensions/ui#idleInterface>

**Comment by ventosus** [comment] 2022-01-30 19:06
The current version shipped with *Parabola GNU/Linux-libre' though, shows the same visibility errors.

    https://www.parabola.nu/packages/community/x86_64/geonkick/

**Comment by ventosus** [comment] 2022-01-30 19:11
@dvzrv have you tried compiling with clang? I'm pretty sure to have encountered GCC versions that just failed to properly hide all C++ symbols.

**Comment by dvzrv** [comment] 2022-01-30 19:58
@ventosus it turns out it is not related to the gcc version, but related to the use of LTO ( `options=(lto)` is the default for Arch build environments now - adds `-flto` to CFLAGS/CXXFLAGS).

Not entirely sure what the best course of action is for this, but probably disable LTO?

**Comment by falkTX** [comment] 2022-01-30 21:20
But that was not an issue with dpf-plugins, which pass lv2lint correct?

**Comment by dvzrv** [comment] 2022-01-30 21:29
> But that was not an issue with dpf-plugins, which pass lv2lint correct?

To my knowledge there I only exclude the `lv2_generate_ttl` stuff (`-s "lv2_generate_ttl"`) and it seems to be fine.

**Comment by TommyAndTheGhosts** [comment] 2022-02-04 07:04
Hi, I'm getting the following using lv2lint for my plugin. I have disabled lto with -fno-lto and I have
  -fPIC
  -fvisibility=hidden

set on my cmakelist.txt
any help appreciated.

```
    [FAIL]  Plugin Instantiation
              failed to instantiate
              seeAlso: <http://lv2plug.in/ns/lv2core>
    [FAIL]  Plugin Symbols
              binary exports superfluous globally visible symbols:
                * _ZTISt19bad_optional_access
                * _ZTSSt19bad_optional_access
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
```

**Comment by TommyAndTheGhosts** [comment] 2022-02-04 07:21
Is using linker script the way to hide symbols now? Since -fvisibility=hidden doesn't hide std symbols it seems like it will only make it more complex to make lv2 plugins hope we can add that to the documentation. I understand why it's necessary though.

**Comment by falkTX** [comment] 2022-02-04 10:36
I think that might be necessary yes, mainly because C++ symbols are not hidden by default.

**Comment by iurienistor** [comment] 2022-02-12 12:02
@ventosus Geonkick uses LV2_INSTANCE_ACCESS_URI. If in the lv2lint code in lv2lint_x11.c I change 

```
const LV2_Feature feat_instance_access = {
	        .URI = LV2_INSTANCE_ACCESS_URI,
                .data = app->instance
        };

to 
```

```
const LV2_Feature feat_instance_access = {
	        .URI = LV2_INSTANCE_ACCESS_URI,
                .data = app->instance->lv2_handle
        };

```
Than the feature passed to the plugin related to LV2_INSTANCE_ACCESS_URI will be correct, and the plugin is not crashing when the UI is tested. Now I have only this output from lv2lint:

```
lv2lint -Mpack -I /usr/local/lib/lv2/geonkick.lv2 "http://geontime.com/geonkick"
lv2lint 0.14.0
Copyright (c) 2016-2021 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
lilv_world_add_plugin(): warning: Reloading plugin <http://geontime.com/geonkick>
lilv_world_add_plugin(): warning: Reloading plugin <http://geontime.com/geonkick/single>
<http://geontime.com/geonkick>
  <http://geontime.com/geonkick#ui>
    [WARN]  UI Instance Access
              usage of instance-access is highly discouraged
              seeAlso: <http://lv2plug.in/ns/ext/instance-access>
    [WARN]  UI Mixed DSP/UI
              mixing DSP and UI code in same binary is discouraged
              seeAlso: <http://lv2plug.in/ns/extensions/ui#>

```

**Comment by falkTX** [comment] 2022-02-12 13:03
warning about instance access is normal. it is a quick way to get an UI up and running, but it will prevent from being used in some scenarios where DSP and UI separation are required. also makes it impossible to sandbox the UI.

**Comment by falkTX** [comment] 2022-02-12 14:45
it is a warning, not an error.
some plugins are simply unable to be split in terms of DSP and UI. doing so for existing plugins typically would involve a complete rewrite, not worth it. such separation needs to be accounted from the start in order to actually work IMO

**Comment by iurienistor** [comment] 2022-02-12 14:48
Since I don't think I have anything to change in the Geonkick code for this issue, I'll close it. Thanks for the comments since this helped me to investigate and fix some potential bugs in Geonkick.

**Closed by iurienistor** 2022-02-12 14:48 UTC

**Comment by ventosus** [comment] 2022-02-13 16:09
On 12.02.22 13:02, Iurie Nistor wrote:
> @ventosus <https://github.com/ventosus> Geonkick uses LV2_INSTANCE_ACCESS_URI. If in the lv2lint code in lv2lint_x11.c I 
> change
> 
> |const LV2_Feature feat_instance_access = { .URI = LV2_INSTANCE_ACCESS_URI, .data = app->instance }; to |
> 
> |const LV2_Feature feat_instance_access = { .URI = LV2_INSTANCE_ACCESS_URI, .data = app->instance->lv2_handle }; |

Oh, thanks, you've found a bug, indeed, will be fixed asap.
